name: Update Portfolio Posts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 경고를 방지하기 위해 24버전으로 명시적 지정

      - name: Install dependencies
        run: npm install node-fetch dotenv

      - name: Run build script
        env:
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}
        run: node build.js

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/posts.json
          git commit -m "Update portfolio posts [skip ci]" || echo "No changes to commit"
          git push
